# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POSIX-Account-LDAP
version:      0.01
version_from: lib/POSIX/Account/LDAP.pm
installdirs:  site
requires:
    Config::Simple:                0
    Net::LDAP:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
